### ISSUE TITLE
Měřitko není potřeba počítat pokaždé znovu

### ISSUE THREAD

**Issue by xtompok** [MazyK11/Du-1#4]
Počítat měřítko stačí jednou na začátku po načtení z klávesnice, není potřeba ho počítat znovu při každém volání podminkarov a podminkapol

**Comment by MazyK11** [comment]
Pokud myslíš tenhle vzorec -> rov = (rov/scale) * 100000; Tak jelikož neznám rov, které se mi vypočítá v každé metodě jiné na základě vzorce, tak to musím počítat pokaždé znovu.

**Comment by xtompok** [comment]
Ale můžeš si rovnou vypočítat to, čím budeš dělit a pak jen dělit jedním
číslem.
Ale i takto je to v pohodě.
